services:
  postgres:
    image: 'postgres:16'
    container_name: minhasreceitas-database-container
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=minhasreceitas
    ports:
      - "5455:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres